plugins {
    id 'java'
    alias(libs.plugins.javafx)
}

version = '1.0'

repositories {
    mavenCentral()
}

javafx {
    version = libs.versions.javafx.get()
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
