package org.masjidku.navigation;

import org.masjidku.accounting.client.model.anakyatim.AnakYatim;
import org.masjidku.accounting.client.model.anakyatim.DonasiAYatim;
import org.masjidku.accounting.client.model.operasional.DonasiOperasional;
import org.masjidku.accounting.client.model.operasional.Operasional;
import org.masjidku.accounting.client.model.pembangunan.DonasiPembangunan;
import org.masjidku.accounting.client.model.pembangunan.Pembangunan;
import org.masjidku.accounting.client.model.tpa.TpaKeluar;
import org.masjidku.accounting.client.model.tpa.TpaMasuk;
import org.masjidku.accounting.client.model.zakat.ZakatKeluar;
import org.masjidku.accounting.client.model.zakat.ZakatMasuk;
import org.masjidku.events.domain.entity.Kegiatan;
import org.masjidku.events.domain.entity.Tamu;
import org.masjidku.events.domain.entity.TamuKegiatan;
import org.masjidku.model.user.User;
import org.masjidku.model.user.UserProfile;

public interface AppRouter {
    void showContent();
    void showLogin();
    void showAbout();
    void recordSession(User user);
    void showProfile();
    void editProfile(UserProfile profile);
    void setAdminView();
    void showAdminHome();
    void showUser();
    void showUserEditScene(User user);
    void showUserLog();
    void setPrincipalView();
    void showPrincipalHome();
    void showLaporan();
    void showKegiatanReport();
    void showAnakYatimReport();
    void showPembangunanReport();
    void showOperasionalReport();
    void showZakatReport();
    void showTpaReport();
    void showData();
    void showKegiatanOverview();
    void showKegiatanData();
    void showTamuData();
    void showUndanganData();
    void showAnakYatimData();
    void showAnakYatimMasuk();
    void showAnakYatimKeluar();
    void showPembangunanData();
    void showPembangunanMasuk();
    void showPembangunanKeluar();
    void showOperasionalData();
    void showOperasionalMasuk();
    void showOperasionalKeluar();
    void showZakatData();
    void showZakatMasuk();
    void showZakatKeluar();
    void showTpaData();
    void showTpaMasuk();
    void showTpaKeluar();
    void setSecretaryView();
    void setSecretaryHome();
    void showKegiatan();
    void showKegiatanEditform(Kegiatan kegiatan);
    void showTamu();
    void showTamuEditForm(Tamu tamu);
    void showUndangan();
    void showUndanganEditForm(TamuKegiatan undangan);
    void setAccountantView();
    void setAccountantHome();
    void showAnakYatim();
    void showDonasiAYatim();
    void showDaftarAnakYatim();
    void editDonaturAnakYatim(DonasiAYatim model);
    void editAnakYatim(AnakYatim model);
    void showZakat();
    void showDonaturZakat();
    void showDaftarPenerimaZakat();
    void editDonaturZakat(ZakatMasuk model);
    void editPenerimaZakat(ZakatKeluar model);
    void showPembangunan();
    void showDonaturPembangunan();
    void showAlokasiPembangunan();
    void editDonaturPembangunan(DonasiPembangunan model);
    void editAlokasiPembangunan(Pembangunan model);
    void showOperasional();
    void showDonaturOperasional();
    void showAlokasiOperasional();
    void editDonaturOperasional(DonasiOperasional model);
    void editAlokasiOperasional(Operasional model);
    void showTpa();
    void showDonaturTpa();
    void showAlokasiTpa();
    void editDonaturTpa(TpaMasuk model);
    void editAlokasiTpa(TpaKeluar model);
    void onLogoutAction();
}
