package org.masjidku.accounting.client.service;

import java.util.List;
import org.masjidku.accounting.client.model.zakat.ZakatMasuk;
import org.masjidku.accounting.client.model.zakat.ZakatKeluar;
import org.masjidku.accounting.client.model.tpa.TpaMasuk;
import org.masjidku.accounting.client.model.tpa.TpaKeluar;
import org.masjidku.accounting.client.model.pembangunan.DonasiPembangunan;
import org.masjidku.accounting.client.model.pembangunan.Pembangunan;
import org.masjidku.accounting.client.model.operasional.DonasiOperasional;
import org.masjidku.accounting.client.model.operasional.Operasional;
import org.masjidku.accounting.client.model.anakyatim.DonasiAYatim;
import org.masjidku.accounting.client.model.anakyatim.AnakYatim;


public interface AccountingClient {
    List<ZakatMasuk> getAllZakatMasuk();
    ZakatMasuk getZakatMasuk(String id);
    boolean isZakatMasukExist(String id);
    void save(ZakatMasuk model);
    void update(ZakatMasuk model);
    void delete(ZakatMasuk model);
    ZakatMasuk getLastZakatMasuk();
    String getTotalZakatMasuk();
    List<ZakatKeluar> getAllZakatKeluar();
    ZakatKeluar getZakatKeluar(String id);
    boolean isZakatKeluarExist(String id);
    void save(ZakatKeluar model);
    void update(ZakatKeluar model);
    void delete(ZakatKeluar model);
    ZakatKeluar getLastZakatKeluar();
    String getTotalZakatKeluar();
    List<TpaMasuk> getAllTpaMasuk();
    TpaMasuk getTpaMasuk(String id);
    boolean isTpaMasukExist(String id);
    void save(TpaMasuk model);
    void update(TpaMasuk model);
    void delete(TpaMasuk model);
    TpaMasuk getLastTpaMasuk();
    String getTotalTpaMasuk();
    List<TpaKeluar> getAllTpaKeluar();
    TpaKeluar getTpaKeluar(String id);
    boolean isTpaKeluarExist(String id);
    void save(TpaKeluar model);
    void update(TpaKeluar model);
    void delete(TpaKeluar model);
    TpaKeluar getLastTpaKeluar();
    String getTotalTpaKeluar();
    List<DonasiPembangunan> getAllDonasiPembangunan();
    DonasiPembangunan getDonasiPembangunan(String id);
    boolean isDonasiPembangunanExist(String id);
    void save(DonasiPembangunan model);
    void update(DonasiPembangunan model);
    void delete(DonasiPembangunan model);
    DonasiPembangunan getLastDonasiPembangunan();
    String getTotalDonasiPembangunan();
    List<Pembangunan> getAllPembangunan();
    Pembangunan getPembangunan(String id);
    boolean isPembangunanExist(String id);
    void save(Pembangunan model);
    void update(Pembangunan model);
    void delete(Pembangunan model);
    Pembangunan getLastPembangunan();
    String getTotalPembangunan();
    List<DonasiOperasional> getAllDonasiOperasional();
    DonasiOperasional getDonasiOperasional(String id);
    boolean isDonasiOperasionalExist(String id);
    void save(DonasiOperasional model);
    void update(DonasiOperasional model);
    void delete(DonasiOperasional model);
    DonasiOperasional getLastDonasiOperasional();
    String getTotalDonasiOperasional();
    List<Operasional> getAllOperasional();
    Operasional getOperasional(String id);
    boolean isOperasionalExist(String id);
    void save(Operasional model);
    void update(Operasional model);
    void delete(Operasional model);
    Operasional getLastOperasional();
    String getTotalOperasional();
    List<DonasiAYatim> getAllDonasiAYatim();
    DonasiAYatim getDonasiAYatim(String id);
    boolean isDonasiAYatimExist(String id);
    void save(DonasiAYatim model);
    void update(DonasiAYatim model);
    void delete(DonasiAYatim model);
    DonasiAYatim getLastDonasiAYatim();
    String getTotalDonasiAYatim();
    List<AnakYatim> getAllAnakYatim();
    AnakYatim getAnakYatim(String id);
    boolean isAnakYatimExist(String id);
    void save(AnakYatim model);
    void update(AnakYatim model);
    void delete(AnakYatim model);
    AnakYatim getLastAnakYatim();
    String getTotalAnakYatim();


    String getInfakYatimBalance();
    String getOperationalBalance();
    String getPembangunanBalance();
    String getTpaBalance();
    String getZakatBalance();
}
