# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
env:
  MYSQL_DATABASE: masjidku
  MYSQL_USER: root
  MYSQL_PASSWORD: root

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        options: >-
          --name=mysql
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        PORT: ${{ job.services.mysql.ports[3306] }}
      run: ./gradlew build

    - name: Verify MySQL Connection
      env:
        PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done

    - name: Test with Gradle
      env:
        PORT: ${{ job.services.mysql.ports[3306] }}
      run: ./gradlew test
